### ISSUE TITLE
Show claim information on transaction page 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/block-explorer#10]
Not sure where exactly, but would be good to link claim information to a transaction:

https://explorer.lbry.io/tx/c8f97c7d6a1f312563d0b624053fb71f5b54cabb6cd3b5865b0e1de74c3d3c4c#output-0

should show: https://explorer.lbry.io/claims/6a0fcce2b1a8103b6eb80c45440f95866113fc63 

or 

should show: https://explorer.lbry.io/claims/21a1dc5fc37e06bf6e551ce52de38f27c0e2cc11
https://explorer.lbry.io/tx/2438dea1ae1622084aa64efe9fa110ee7136e16d551e74a93baa9fca3445fd2a#output-0

**Comment by akinwale** [comment]
I initially thought of linking the CLAIM label to the claim itself, but I suppose we could also add a popover toggled on click or hover which shows a summary of the claim details.
