### ISSUE TITLE
Fix URL Encoded LBRY links from explorer

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/block-explorer#23]
https://explorer.lbry.io/claims/6bbd31d0e1bcbcf7735ff7b35bcca322a24ec64b

When clicking open in LBRY, the app fails to open the file because of a % in the URL. 

https://open.lbry.io/@unclejed613/lbry2 works but https://open.lbry.io/%40unclejed613%2Flbry2 does not.

**Comment by Invariant-Change** [comment]
There is also HTML being outputting over the thumb.

![image](https://user-images.githubusercontent.com/29914179/39509726-a5da5900-4e2a-11e8-992f-310d6fd683f2.png)
![image](https://user-images.githubusercontent.com/29914179/39509823-f682153c-4e2a-11e8-8057-86651eb38163.png)

**Comment by Invariant-Change** [comment]
@tzarebczan Further to this. Both links in example above work, maybe you meant this link from the **Open in LBRY** button, which breaks the app for me?

lbry://%40unclejed613/lbry2 w

**Comment by tzarebczan** [comment]
Yes, that's what this issue is for  - when clicking Open in LBRY the app doesn't handle some of the encoding currently. 

Opened https://github.com/lbryio/block-explorer/issues/25 for the html issue.

**Comment by marcdeb1** [comment]
This claim had a thumbnail with html characters (<img src="..."/>). Issue is fixed by escaping html characters.

**Comment by alyssaoc** [comment]
@akinwale Can you confirm if this has been fixed?

**Comment by tiger5226** [comment]
fixed
