### ISSUE TITLE
Use Chainquery

### ISSUE THREAD

**Issue by kauffj** [lbryio/block-explorer#28]
[chainquery](https://github.com/lbryio/chainquery) ought to make the explorer easier to work with/use and simpler to maintain (if _doesn't_ do that, that is also useful feedback for chainquery).

**Comment by marcdeb1** [comment]
I am ready to take up the task, it could make the explorer much simpler and solve issues such as #8. As @tiger5226 suggested, there could be a direct DB connection to Chainquery.

**Comment by tiger5226** [comment]
I can setup the credentials for you. Ultimately, the block explorer is a great candidate to integrate with Chainquery. It was actually what I started from for Chainquery. So it should be a very close match on the schema. I would not expect many differences.

**Comment by tiger5226** [comment]
@marcdeb1 Testing credentials for Chainquery have been sent over. When we are ready to deploy we can setup a production account for the explorer.

**Comment by tiger5226** [comment]
It would be nice if we aligned across the organization. Chainquery schema in the standard now, so we should probably align on that. I think currently let's not break an api's but we should create an issue to address this with a long term solution that could include api versioning. Ultimately, block information should just come from chainquery api's. So we will probably want to deprecate the apis from the block explorer altogether. Block explorer should just be a pretty ui for chainquery data.

**Comment by tiger5226** [comment]
Solved with Chainquery integration
