### ISSUE TITLE
cache supply endpoint daily?

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/block-explorer#29]
This query takes a few seconds to run - maybe we can cache the results daily? 

https://explorer.lbry.io/api/v1/supply

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tiger5226** [comment]
This was fixed with the latest chainquery integration. The endpoint is very fast now.
