### ISSUE TITLE
incorrect incoming tx / amount 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/block-explorer#3]
Sent you this one a while ago: https://explorer.lbry.io/address/bXikZS1g1jvjV1vSB83nPkaEXGZTKoms4f

Looks like it should only have 1 input from: https://explorer.lbry.io/tx/8694118779e15f97bbc79803a67e1f67528f1f6d0aaa5172bb473774aaa72328?address=bXikZS1g1jvjV1vSB83nPkaEXGZTKoms4f#bXikZS1g1jvjV1vSB83nPkaEXGZTKoms4f because the other one links to this tx: https://explorer.lbry.io/tx/0cb62edff9a3ec4478f0a8b8b57b227142cee626c559f5352a54fb333fec17ca?address=bXikZS1g1jvjV1vSB83nPkaEXGZTKoms4f#bXikZS1g1jvjV1vSB83nPkaEXGZTKoms4f which shows 0 coming from that address. 

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tiger5226** [comment]
Solved with Chainquery integration
