### ISSUE TITLE
Search issues

### ISSUE THREAD

**Issue by jsigwart** [lbryio/block-explorer#39]
When I use the search function, I have various issues:

* Numeric searches seem to be assumed to be a block number search. If I search for a filename that is numeric, the result returned may be a block number or nothing at all (because the block numbers don't go that high?)
* If there are more than one entry for a filename, no results are returned. I should get multiple results to choose from.
* If no results are returned for whatever reason, it doesn't tell me there is an error or no results. It just displays the explorer home page.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by marcdeb1** [comment]
Good ideas, a numeric search is indeed assumed to be a block. Maybe we can check if the number is smaller than the last block number, but there would be a conflict for small numbers. Another option could be to add a symbol for block search, such as #121 if I want to search for block number 121. That would be indicated in the placeholder.

**Comment by tiger5226** [comment]
>Numeric searches seem to be assumed to be a block number search. If I search for a filename that is numeric, the result returned may be a block number or nothing at all (because the block numbers don't go that high?)

I think this is fine until we want some more advanced searching capabilities, after all it is the block explorer. 

>If there are more than one entry for a filename, no results are returned. I should get multiple results to choose from.

This is no longer the case. See screenshot below:

<img width="1405" alt="Screen Shot 2019-03-18 at 10 44 40 PM" src="https://user-images.githubusercontent.com/3402064/54576667-80d4d300-49cf-11e9-8883-44e15fde441c.png">

>If no results are returned for whatever reason, it doesn't tell me there is an error or no results. It just displays the explorer home page.

This is now fixed. See screenshot below:

<img width="1410" alt="Screen Shot 2019-03-18 at 10 43 17 PM" src="https://user-images.githubusercontent.com/3402064/54576690-94803980-49cf-11e9-8ed6-7553a1437b00.png">
