### ISSUE TITLE
# of confirmations incorrect

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/block-explorer#4]
I've noticed this on a couple addresses, but here is one example: https://explorer.lbry.io/address/bRgPS3mfWTGhK6qsoeGjnCAfwakQvmpWpt 

You can see that the # of confirmations are not consistent. You had mentioned this could be an issue with the SQL query as the blocks themselves have the right # confirmations.

**Comment by akinwale** [comment]
This is fixed in https://github.com/lbryio/block-explorer/commit/b91b3681d371c8254b987abaae3bc9403955de96
