### ISSUE TITLE
incorrect claim opens when using "view" button on tx page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/block-explorer#45]
https://explorer.lbry.io/tx/ffc95e511018815157c2a63c1818e16e9c61d8fe5a4fe7545264126e57dc7a39

Shows: https://explorer.lbry.io/claims/145ca931f4478344b2c1f6cd9a8359c00fe90430

Correct claim: ef3dbbed10ec1b72e38f7c712a4242c9995ff9d8

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tiger5226** [comment]
Solved with Chainquery integration
