### ISSUE TITLE
Ensure old URLs work

### ISSUE THREAD

**Issue by kauffj** [lbryio/block-explorer#54]
I merged https://github.com/lbryio/lbry.tech/pull/254 and this encouraged me to test if the old URL formats properly redirected. They did not appear to, but they should.

**Comment by kauffj** [comment]
@tzarebczan can you do this or does @tiger5226 or @akinwale need to?

**Comment by tzarebczan** [comment]
That was my bad, it's a bug on lbry.tech. Will submit a fix.

**Comment by tzarebczan** [comment]
Fixed.
