### ISSUE TITLE
Disable viewing of blocked data

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/block-explorer#71]
Similar to our other apps, the explorer should also abide by the block list. It should not be possible to see blocked claim metadata. This should be done at both the claim and channel level.

**Comment by tzarebczan** [comment]
This data is also indexed on google so we should block it asap.

**Comment by kauffj** [comment]
This repo isn't really going through sprint planning at the moment, but probably should be done when @akinwale and I look at mobile issues.
