### ISSUE TITLE
Genesis address shows balance, should be 0

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/block-explorer#8]
https://explorer.lbry.io/address/bHW58d37s1hBjj3wPBkn5zpCX3F8ZW3uWf - should say 0. 

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tiger5226** [comment]
Solved with Chainquery integration
