### ISSUE TITLE
Claim searching not working

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/block-explorer#9]
When typing 6a0fcce2b1a8103b6eb80c45440f95866113fc63 in the search, it returns you at the home page.

Would expect this result: 
https://explorer.lbry.io/claims/6a0fcce2b1a8103b6eb80c45440f95866113fc63

**Comment by akinwale** [comment]
This is probably due to a case where the claim hasn't been indexed yet. Ideally, we should create a search results page which indicates results that could not be found.

**Comment by tzarebczan** [comment]
@akinwale I don't think that's the case- I searched for it now and it doesn't come up either. It just returns to the main explorer page.

**Comment by tiger5226** [comment]
This is no longer an issue with the chainquery integration.
